[package]
name = "burn_app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# No external dependencies needed for this simple example

[profile.release]
# Optimize for small code size
opt-level = "s"
lto = true
